Fix Downloads Check
When running in firefox, if we search we get the following error:

```
ReferenceError: chrome is not defined
```

This is because the chrome extension API is only available in the chrome
browser. Let's add a little check for the folks using other browsers.